ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  DATA_PATH: /home/ghadeer/Projects/Neural-SLAM/habitat-lab/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DATA_PATH: /home/ghadeer/Projects/Neural-SLAM/habitat-lab/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
DATASET:
  DATA_PATH: /home/ghadeer/Projects/Neural-SLAM/habitat-lab/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz

DATA_PATH: /home/ghadeer/Projects/Neural-SLAM/habitat-lab/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz
